app/home/__init__.py
# app/home/__init__.py

from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
# app/home/views.py

from flask import render_template
from flask_login import login_required, current_user

from . import home

@home.route('/')
def homepage():
    """
    Render the homepage template on the / route
    """
    return render_template('home/index.html', title="Welcome")

@home.route('/about')
def about():
    """
    Render the about template on the /about route
    """
    return render_template('home/about.html', title="About Us")

@home.route('/team')
def team():
    """
    Render the team template on the /team route
    """
    return render_template('home/team.html', title="Our Team")

@home.route('/services')
def services():
    """
    Render the services template on the /services route
    """
    return render_template('home/services.html', title="Our Services")

@home.route('/contact')
def contact():
    """
    Render the homepage template on the / route
    """
    return render_template('home/contact.html', title="Contact page")

@home.route('/dashboard')
@login_required
def dashboard():
    """
    Render the dashboard template on the /dashboard route
    """
    return render_template('blog/dash_index.html', title="Blog Dashboard")

# add admin dashboard view
@home.route('/admin/dashboard')
@login_required
def admin_dashboard():
    # prevent non-admins from accessing the page
    if not current_user.is_admin:
        abort(403)

    return render_template('admin/dash.html', title="Admin Dashboard")

app/templates/home/about.html
<!-- app/templates/home/about.html -->

{% extends "base.html" %}
{% block title %}About Us{% endblock %}
{% block body %}

    <main id="main">

        
    
         <!-- ======= About Us Section ======= -->
    <section id="testimonials" class="about-us">
      <div class="container" data-aos="fade-up">
        <div class="section-title">
          <h2>Overview</strong></h2>
        </div>
        <div class="row content">
          <div class="col-lg-6" data-aos="fade-right">
            
            <div class="testimonial-item">
              <img src="static/img/testimonials/maathai_lecture.jpg" class="testimonial-img" style="justify-content: center;" alt="">
              <p>
                <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                You cannot protect the environment unless you empower people, you inform them, and you help them understand that these resources are their own, that they must protect them.
                <i class="bx bxs-quote-alt-right quote-icon-right"></i>
              </p>
              <h3>-Wangari Maathai.</h3>
              <h4>(2004 Nobel Peace Prize,</h4>
              <h4>Kenyan environmental activist.)</h4>
              
            </div>
          </div>
          <div class="col-lg-6 pt-4 pt-lg-0" data-aos="fade-left">
            <p>
              ISOTOPE CONSULTANCY LIMITED is committed to setting the highest standards for service delivery and performance in environmental impact assessments and audits as well as consultancy services on environmental conservation and management.
            </p>
            <P>The following outline the basic services provided by the Firm:</P>
            <ul>
              <li><i class="ri-check-double-line"></i> Environmental and Social Impact Assessment (ESIA)</li>
              <li><i class="ri-check-double-line"></i> Environmental Management Plan (EMP)</li>
              <li><i class="ri-check-double-line"></i> Environmental Audit (EA)</li>
              <li><i class="ri-check-double-line"></i> Environmental Policy and Legislative Compliance Application</li>
            </ul>
            <p class="font-italic">
              The Firm of Experts, given their knowledge in the existing environmental policies, laws and regulations will produce high quality, time and more cost-effective EIA and EA reports.
            </p>
          </div>
        </div>

      </div>
    </section><!-- End About Us Section -->
    
       <!-- ======= About Us Section ======= -->
    <section id="faq" class="faq section-bg">
      <div class="container"  data-aos="fade-up">

        <div class="section-title">
          <h2>About Us</h2>
        </div>

        <div class="faq-list">
          <ul>
            <li data-aos="fade-up" >
              <i class="bx bxs-book-bookmark icon-help"></i> <a data-toggle="collapse" href="#faq-list-5" >REGISTRATION <i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
              <div id="faq-list-5" class="collapse show" data-parent=".faq-list">
                <p>
                  The company is duly registered under the Companies Act 2015 of the Laws of Kenya and incorporated here in Kenya as a Private Limited Liability Company. We are also registered with the Ministry of Finance (Kenya Revenue Authority). 
                </p>
              </div>
            </li>
            <li data-aos="fade-up" data-aos-delay="50">
              <i class="bx bx-grid icon-help"></i> <a data-toggle="collapse" class="collapsed" href="#faq-list-1" >Setting Project Goals <i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
              <div id="faq-list-1" class="collapse" data-parent=".faq-list">
                <p>
                  The Firm of Experts will always thoroughly familiarize themselves with the project/ activity complexities through site visits and site meetings with the stakeholders and any other parties involved in projects to ensure public participation.  These meetings are useful in reviewing projects/ activities and lines of authority as well as establishing project procedures and rules, while identifying possible impacts a particular project/ activity might have on the environment. 
                  Thereafter, a work plan will be developed to facilitate easy co-ordination of environmental assessments and/or audits which will guide in developing an EMP for project implementation or otherwise according to the verdict that will be given by National Environment Management Authority (NEMA).  
                </p>
              </div>
            </li>

            <li data-aos="fade-up" data-aos-delay="100">
              <i class="bx bx-disc icon-help"></i> <a data-toggle="collapse" href="#faq-list-2" class="collapsed">Information and Documentation <i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
              <div id="faq-list-2" class="collapse" data-parent=".faq-list">
                <p>
                  ISOTOPE CONSULTANCY LIMITED believes in maintaining records to facilitate easy documentation and retrieval of any information required at project/ activity site and office.  It includes reports for project/ activity site meetings which focus on action items for each of the participants.  
                  The action items guide the entire process of ESIA and/or EA and can be tracked and managed by the Experts to ensure they are implemented to completion during project/activity process.
                  The final EIA and/or EA report will be forwarded to NEMA complete with EMP for every project/activity verified and signed by all Experts who participated in the exercise. 
                </p>
              </div>
            </li>

            <li data-aos="fade-up" data-aos-delay="200">
              <i class="bx bx-diamond icon-help"></i> <a data-toggle="collapse" href="#faq-list-3" class="collapsed">Establishment and Monitoring Quality <i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
              <div id="faq-list-3" class="collapse" data-parent=".faq-list">
                <p>
                  ISOTOPE CONSULTANTS LIMITED is committed to timely delivery of services and any other item that require its attention as required and when needed.  Similarly, the Firm of Experts is responsible for co-ordination of sampling and testing of all required materials as set out in the environmental laws, policies, regulations and standard specification requirements.
                  During every operation, Firm of Experts will check standard procedures and observe the entire process to meet the stipulated environmental standards such as ISO 14001:2015 Environmental Management systems.
                </p>
              </div>
            </li>

            <li data-aos="fade-up" data-aos-delay="300">
              <i class="bx bx-layer icon-help"></i> <a data-toggle="collapse" href="#faq-list-4" class="collapsed">Commitment to Health, Safety and the Environment <i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
              <div id="faq-list-4" class="collapse" data-parent=".faq-list">
                <p>
                  Activities of ISOTOPE CONSULTANCY LIMITED are executed in accordance with the guidelines provided by the Government and the National Environment Management Authority (NEMA) as well as our comprehensive company policies and procedures and other relevant legislations.
The Firm implements the occupational health and safety requirements and delegate obligations to the Experts to ensure compliance at the projects/activity site(s).
                </p>
              </div>
            </li>

            <li data-aos="fade-up" data-aos-delay="400">
              <i class="bx bx-hash icon-help"></i> <a data-toggle="collapse" href="#faq-list-6" class="collapsed">PHYSICAL IDENTIFICATION <i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
              <div id="faq-list-6" class="collapse" data-parent=".faq-list">
                <p>
                  The company Head office is located in Eldoret Kenya at Sagatia Business Centre, Room F7 Elgeyo Road in Uasin Gishu County and has a branch office at Tabut House in Iten town, Elgeyo Marakwet County. 
                </p>
              </div>
            </li>

            

          </ul>
        </div>

      </div>
    </section><!-- End Frequently Asked Questions Section -->
    {% include 'partials/clients.html' %}
  

{% endblock %}

app/templates/home/admin_dashboard.html
<!-- app/templates/home/admin_dashboard.html -->

{% extends "base.html" %}
{% block title %}Admin{% endblock %}
{% block body%}
<main id="main">
    
      
      <div class="container-fluid">
        <div class="row">
          <nav id="sidebarMenu " class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
            <div class="position-sticky pt-3">
              <ul class="nav flex-column">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{{ url_for('home.admin_dashboard') }}">
                    <span data-feather="home"></span>
                    Admin Dashboard
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">
                    <span data-feather="file"></span>
                    Isotope
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">
                    <span data-feather="shopping-cart"></span>
                    Services
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">
                    <span data-feather="users"></span>
                    Users
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">
                    <span data-feather="bar-chart-2"></span>
                    Staff
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('admin.list_roles') }}">
                    <span data-feather="layers"></span>
                    Roles
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('home.dashboard') }}">
                    <span data-feather="file"></span>
                    Blog
                  </a>
                </li>
              </ul>
      
              <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                <span>Saved reports</span>
                <a class="link-secondary" href="#" aria-label="Add a new report">
                  <span data-feather="plus-circle"></span>
                </a>
              </h6>
              <ul class="nav flex-column mb-2">
                <li class="nav-item">
                  <a class="nav-link" href="#">
                    <span data-feather="file-text"></span>
                    Current month
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">
                    <span data-feather="file-text"></span>
                    Last quarter
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">
                    <span data-feather="file-text"></span>
                    Social engagement
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">
                    <span data-feather="file-text"></span>
                    Year-end sale
                  </a>
                </li>
              </ul>
            </div>
          </nav>
      
          <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
              {{ title }}
              <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-group me-2">
                  <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
                </div>
                <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
                  <span data-feather="calendar"></span>
                  This week
                </button>
              </div>
            </div>
            
            <!--<canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas> -->
            {% block admin %}

            {% endblock %}
           
          </main>
        </div>
      </div>
    
</main>
{% endblock %}

app/templates/home/contact.html
<!-- app/templates/home/contact.html -->

{% extends "base.html" %}
{% block title %}Contact Us{% endblock %}
{% block body %}
<main id="main">

  

    <!-- ======= Contact Section ======= -->
    <div class="map-section">
      <iframe width="100%" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q=SAGATIA%20BUSINESS%20CENTRE%20ELDORET&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
    </div>

    <section id="contact" class="contact">
      <div class="container">

        <div class="row justify-content-center" data-aos="fade-up">

          <div class="col-lg-10">

            <div class="info-wrap">
              <div class="row">
                <div class="col-lg-4 info">
                  <i class="icofont-google-map"></i>
                  <h4>Location:</h4>
                  <p>Sagatia Business Centre,<br>Elgeyo Road,<br> Uasin Gishu County.</p>
                </div>

                <div class="col-lg-4 info mt-4 mt-lg-0">
                  <i class="icofont-envelope"></i>
                  <h4>Email:</h4>
                  <p>isotopeconsultants@gmail.com<br>mail us.</p>
                </div>

                <div class="col-lg-4 info mt-4 mt-lg-0">
                  <i class="icofont-phone"></i>
                  <h4>Call:</h4>
                  <p>+254723744242<br>call us.</p>
                </div>
              </div>
            </div>

          </div>

        </div>

        <div class="row mt-5 justify-content-center" data-aos="fade-up">
          <div class="col-lg-10">
            <form action="forms/contact.php" method="post" role="form" class="php-email-form">
              <div class="form-row">
                <div class="col-md-6 form-group">
                  <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                  <div class="validate"></div>
                </div>
                <div class="col-md-6 form-group">
                  <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
                  <div class="validate"></div>
                </div>
              </div>
              <div class="form-group">
                <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
                <div class="validate"></div>
              </div>
              <div class="form-group">
                <textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Message"></textarea>
                <div class="validate"></div>
              </div>
              <div class="mb-3">
                <div class="loading">Loading</div>
                <div class="error-message"></div>
                <div class="sent-message">Your message has been sent. Thank you!</div>
              </div>
              <div class="text-center"><button type="submit">Send Message</button></div>
            </form>
          </div>

        </div>

      </div>
    </section><!-- End Contact Section -->

  </main><!-- End #main -->
{% endblock %}

app/templates/home/dashboard.html
<!-- app/templates/home/dashboard.html -->

{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<main id="main">

   

    <!-- ======= Dashboard Section ======= -->
    <section id="blog" class="blog">
      <div class="container">

        <div class="row">
          

          <div class="col-lg-4 ">
            
            <div class="sidebar" data-aos="fade-right">
              
                <h3 class="sidebar-title">Search</h3>
              <div class="sidebar-item search-form">
                <form action="">
                  <input type="text">
                  <button type="submit"><i class="icofont-search"></i></button>
                </form>

              </div><!-- End sidebar search formn-->
              <div class="sidebar-title">
                <a href="{{ url_for('home.dashboard') }}"><i class="fa fa-user"></i>  Hi, {{ current_user.username }}!</a>
                <br>
                
               
               
              </div>
              <h3 class="sidebar-title">Blog Actions</h3>
              <div class="sidebar-item categories">
                <ul>

                  <li><a href="{{ url_for('blog.add_article') }}">New Article </a></li>
                  <li><a href="{{ url_for('blog.list_articles') }}">View Articles </a></li>
                  <li><a href="/cartegories">Cartegories </a></li>
                  
                  <li><a href="/drafts">Drafts</a></li>
                  
                </ul>

              </div><!-- End sidebar categories-->
              
              

              
              

              

            </div><!-- End sidebar -->

          </div><!-- End blog sidebar -->

                
            
  
          

    <div class="col-lg-8 "><!---->

             <!-- ======= Page content section ======= -->
    <section id="services" class="services section-bg">
        <div class="container" data-aos="fade-up">
          {% block blog %}

          {% endblock %}
         
  
        </div>
      </section><!-- End Services Section -->
        </div>
        </div>
      </div>
    </section>

{% endblock %}

app/templates/home/index.html
<!-- app/templates/home/index.html -->

{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<!-- ======= Hero Section ======= -->
<section id="hero">
    <div id="heroCarousel" class="carousel slide carousel-fade" data-ride="carousel">

      <div class="carousel-inner" role="listbox">

        <!-- Slide 1 -->
        <div class="carousel-item active" style="background-image: url(static/img/slide/slide-1.jpg);">
          <div class="carousel-container">
            <div class="carousel-content animate__animated animate__fadeInUp">
              <h2>Welcome to <span>Isotope Consultancy Limited</span></h2>
              <p>We are a Consultancy Firm of Environmental Experts registered under the Companies Act 2015 seeking to promote environmental conservation and management.</p>
              <div class="text-center"><a href="" class="btn-get-started">Read More</a></div>
            </div>
          </div>
        </div>

        <!-- Slide 2 -->
        <div class="carousel-item" style="background-image: url(static/img/slide/slide-2.jpg);">
          <div class="carousel-container">
            <div class="carousel-content animate__animated animate__fadeInUp">
              <h2>Our Mission</h2>
              <p>To offer environmental consultancy, impact assessments and audit services to ensure compliance to legal requirements and international standards.</p>
              <div class="text-center"><a href="" class="btn-get-started">Read More</a></div>
            </div>
          </div>
        </div>

        <!-- Slide 3 -->
        <div class="carousel-item" style="background-image: url(static/img/slide/slide-3.jpg);">
          <div class="carousel-container ">
            <div class="carousel-content animate__animated animate__fadeInUp">
              <h2>Our Vision</h2>
              <p>To be a global leader in professional environmental and social impact assessment and audit consultancies for conservation and management.</p>
              <div class="text-center"><a href="" class="btn-get-started">Read More</a></div>
            </div>
          </div>
        </div>

      </div>

      <a class="carousel-control-prev" href="#heroCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon icofont-simple-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>

      <a class="carousel-control-next" href="#heroCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon icofont-simple-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>

      <ol class="carousel-indicators" id="hero-carousel-indicators"></ol>

    </div>
  </section><!-- End Hero -->
    <!-- ======= About Us Section ======= -->
    <section id="about-us" class="about-us">
      <div class="container" data-aos="fade-up">
        <div class="section-title">
          <h2>Services Overview</strong></h2>
        </div>
        <div class="row content">
          <div class="col-lg-6" data-aos="fade-right">
            <h2>“One of the first conditions of happiness is that the link between man and nature shall not be broken.”</h2>
            <h3 style="text-align:center;">—Leo Tolstoy</h3>
          </div>
          <div class="col-lg-6 pt-4 pt-lg-0" data-aos="fade-left">
            <p>
              ISOTOPE CONSULTANCY LIMITED is committed to setting the highest standards for service delivery and performance in environmental impact assessments and audits as well as consultancy services on environmental conservation and management.
            </p>
            <P>The following outline the basic services provided by the Firm:</P>
            <ul>
              <li><i class="ri-check-double-line"></i> Environmental and Social Impact Assessment (ESIA)</li>
              <li><i class="ri-check-double-line"></i> Environmental Management Plan (EMP)</li>
              <li><i class="ri-check-double-line"></i> Environmental Audit (EA)</li>
              <li><i class="ri-check-double-line"></i> Environmental Policy and Legislative Compliance Application</li>
            </ul>
            <p class="font-italic">
              The Firm of Experts, given their knowledge in the existing environmental policies, laws and regulations will produce high quality, time and more cost-effective EIA and EA reports.
            </p>
          </div>
        </div>

      </div>
    </section><!-- End About Us Section -->

    {% include 'partials/clients.html' %}

{% endblock %}

app/templates/home/services.html
<!-- app/templates/home/services.html -->

{% extends "base.html" %}
{% block title %}Our Services{% endblock %}
{% block body %}
<main id="main">

    

    <!-- ======= Services Section ======= -->
    <section id="services" class="services section-bg">
      <div class="container" data-aos="fade-up">
        <div class="section-title">
          <h2>Our Services
          
          </h2>
          <p>Through experienced leadership and attention to detail, the Consultancy Company ensures the success of our clients’ objectives without compromising their surrounding environment. </p>
        </div>
        
        <div id="accordion">
          <div class="card mb-3">
            <div class="card-header" id="headingOne">
              <h5 class="mb-0">
                <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                  Environmental and Social Impact Assessment (ESIA)
                </button>
              </h5>
            </div>
        
            <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
              <div class="card-body">
                This process is a way to identify, predict and assess the type and scale of. potential biodiversity impacts, and opportunities to benefit conservation, associated with any business activities or projects. Biodiversity assessment should begin as early as possible, as effective assessment of the biodiversity characteristics of an area — and
                the potential impacts — may require months or even years, to account for seasonal and migration issues. In addition, early attention to
                biodiversity issues means that potential impacts can be identified and avoided or mitigated in the earliest stages of planning. Once a
                project or business activity proceeds, the costs of redesign or re-siting will make it more difficult to effectively address biodiversity issues           </div>
            </div>
          </div>
          <div class="card mb-3">
            <div class="card-header" id="headingTwo">
              <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                  Environmental Management Plan (EMP)
                </button>
              </h5>
            </div>
            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
              <div class="card-body">
                An environmental
                          management tool used to ensure that
                                      undue or reasonably avoidable adverse
                          impacts of the construction, operation and
                                      decommissioning of a project are
                                prevented; and that the positive benefits of
                                  the projects are enhanced. EMPs are
                                  therefore important tools for ensuring that
                                  the management actions arising from
                                  Environmental Impact Assessment (EIA)
                                  processes are clearly defined and
                                  implemented through all phases of the
                                  project life-cycle. 
              </div>
            </div>
          </div>
          <div class="card mb-3">
            <div class="card-header" id="headingThree">
              <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                  Environmental Audit (EA)
                </button>
              </h5>
            </div>
            <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
              <div class="card-body">
                Environmental Audit (EA) is the systematic documented, periodic and objective evaluation of how activities and processes of an ongoing project to determine how far these activities and programs conform with the approved environmental management plan of that specific project and sound environmental management practices.  A comprehensive EA promotes safe and healthy environment at all stages of a project operations, as well as decommissioning. The goal of EA is to establish if proponents of projects are complying with environmental requirements and enforcing legislation. An environmental auditor shall appraise all project activities, including the production of goods and services, taking into consideration environmental regulatory frameworks, environmental standards, environmental health and safety measures and sustainable use of natural resources.
              </div>
            </div>
          </div>
          <div class="card mb-3">
            <div class="card-header" id="headingFour">
              <h5 class="mb-0">
                <button class="btn btn-link" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                  Environmental Policy and Legislative Compliance Application
                </button>
              </h5>
            </div>
        
            <div id="collapseFour" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
              <div class="card-body">
                Environmental policy is the commitment of an organization or government to the laws, regulations, and other policy mechanisms concerning environmental issues. These issues generally include air and water pollution, waste management, ecosystem management, maintenance of biodiversity, the management of natural resources, wildlife and endangered species. For example, concerning environmental policy, the implementation of an eco-energy-oriented policy at a global level to address the issues of global warming and climate changes could be addressed. Policies concerning energy or regulation of toxic substances including pesticides and many types of industrial waste are part of the topic of environmental policy. This policy can be deliberately taken to influence human activities and thereby prevent undesirable effects on the biophysical environment and natural resources, as well as to make sure that changes in the environment do not have unacceptable effects on humans.
              </div>
            </div>
          </div>
          
         
        </div>
      </div>
    </section><!-- End Services Section -->
   
    {% include 'partials/clients.html' %}

  </main><!-- End #main -->

{% endblock %}