app/blog/forms.py
# app/blog/forms.py

from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, TextAreaField, SubmitField, ValidationError, RadioField, BooleanField, validators, IntegerField
from wtforms.validators import DataRequired, Email, EqualTo, Length

class ArticleForm(FlaskForm):
    """
    Form for user to add or edit an article
    """
    
    title = StringField('Title', [validators.Length(min=1, max=200,message='Too short or too long')]) 
    author = StringField('Author', [validators.DataRequired()])
    body = TextAreaField('Body', [validators.Length(min=30)])
    tags = StringField('Tags', [validators.DataRequired()])
    draft = BooleanField('Publish')
    submit = SubmitField('Submit')

class CartegoryForm(FlaskForm):
    """
    Form for admin to add or edit cartegories
    """
    name = StringField('Name', validators=[DataRequired()])
    description = StringField('Description', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/blog/__init__.py
# app/blog/__init__.py

from flask import Blueprint

blog = Blueprint('blog', __name__)

from . import views

app/blog/views.py
# app/blog/views.py

from flask import abort, flash, redirect, render_template, url_for
from flask_login import current_user, login_required
from flask_sqlalchemy import SQLAlchemy


from . import blog
from .forms import ArticleForm, CartegoryForm
from .. import db 
from ..models import Article, Cartegory

@blog.route('/blog')
def blogpage():
    """
    Render the blogpage template on the / route
    """
    articles = Article.query.all()

    return render_template('blog/blog.html', title="Blog", articles=articles)

@blog.route('/page')
def blogsinglepage():
    """
    Render the blogpage template on the /page route
    """
    return render_template('blog/single.html', title="Blog Page")

@blog.route('/list_articles')
@login_required
def list_articles():
    """
    List articles from database
    """

    articles = Article.query.all()
    return render_template('blog/articles.html', title="Articles", articles=articles)

@blog.route('/add_article', methods=['GET', 'POST'])
@login_required
def add_article():
    """
    Add article to database
    """

    add_article = True
    
    form = ArticleForm()
    if form.validate_on_submit():
        article = Article(title=form.title.data,
                            author=form.author.data,
                            body=form.body.data,
                            tags=form.tags.data,
                            draft=form.draft.data)
        try:
            #add article to the database
            db.session.add(article)
            db.session.commit()
            flash('You have successfully added a new article')
        except:
            #in case article submissin fails
            flash('Error: An error occured submitting your article.')

        # redirect to articles page
        return redirect(url_for('blog.list_articles')) 

    return render_template('blog/article.html', action="Add",add_article=add_article, form=form, title="New Article")


@blog.route('/articles/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_article(id):
    """
    Edit an article
    """
    

    add_article = False

    article = Article.query.get_or_404(id)
    form = ArticleForm(obj=article)
    if form.validate_on_submit():
        article.title=form.title.data,
        article.author=form.author.data,
        article.body=form.body.data,
        article.tags=form.tags.data,
        article.draft=form.draft.data

        
        db.session.commit()
        flash('You have successfully edited article.')

        # redirect to the articles page
        return redirect(url_for('blog.list_articles'))

    form.title.data=article.title
    form.author.data=article.author
    form.body.data=article.body
    form.tags.data=article.tags
    form.draft.data=article.draft
    return render_template('blog/article.html', action="Edit", add_article=add_article,
                           form=form, title="Edit Article")

@blog.route('/articles/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_article(id):
    """
    Delete an article from the database 
    """

    article = Article.query.get_or_404(id)

    db.session.delete(article)
    db.session.commit()
    flash('You have successfully deleted the article')

    # redirect to the articles page
    return redirect(url_for('blog.list_articles'))
    

    return render_template(title="Delete Article")

app/templates/blog/article.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "home/dashboard.html" %}
{% block title %}
    {% if add_article %}
        Add Article
    {% else %}
        Edit Article
    {% endif %}
{% endblock %}

{% block blog %}

    {% if add_article %}
        <h3>Add Article</h3>
        <form method="POST" role="form"  action="{{ url_for('blog.add_article') }}">
    {% elif add_article=='False' %}
        <h3>Edit Article</h3>
        <form method="POST" role="form"  action="{{ url_for('blog.edit_article') }}">
    {% endif %}
        
            
            
              {{ form.csrf_token() }}
               
           
                
                <div class="form-group">


               
                {{ wtf.form_field(form.title, class='form-control', 
                placeholder='Title') }}
            
              </div>
              <div class="form-group" >


               
                {{ wtf.form_field(form.body, class='form-control', 
                placeholder='Body', id="editor") }}
            
              </div>
              
              <div class="form-group">


                
                {{ wtf.form_field(form.tags, class='form-control', 
                placeholder='One, Two, Three') }}
            
              </div>
              <div class="form-group">


            
                {{ wtf.form_field(form.draft, class='form-control', 
                placeholder='Is Draft?') }}
            
              </div>
              <div class="form-group">


            
                {{ wtf.form_field(form.author, class='form-control', 
                placeholder='Author') }}
            
              </div>

              <input type="submit" value="submit" />
              <button type="submit">Submit</button>
            
                  
            </form>
      
   

{% endblock %}

app/templates/blog/articles.html
{% import "bootstrap/utils.html" as utils %}
{% extends "home/dashboard.html" %}
{% block title %}List Article{% endblock %}

{% block blog %}
<div>
    {{ utils.flashed_messages() }}
    <div>
        {% if articles %}
        <div>
<table class="table-responsive table-hover">
    <thead class="thead-dark">
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Title</th>
        <th scope="col">Author</th>
        
        <th scope="col">Date</th>
        <th scope="col">Published</th>
        <th scope="col">Tags</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
        {% for article in articles %}
      <tr >
        <th onclick="{{ url_for('blog.edit_article', id=article.id) }}" scope="row">{{article.id }}</th>
        <td>{{article.title}}</td>
        <td>{{article.author}}</td>
        
        <td>{{article.date}}</td>
        <td>{{article.draft}}</td>
        <td>{{article.tags}}</td>
        <td><a href="{{ url_for('blog.edit_article', id=article.id) }}">   
                  <i class="fa fa-pencil"></i> Edit
                    </a>
        </td>
        <td>
            <a href="{{ url_for('blog.delete_article', id=article.id) }}">
              <i class="fa fa-trash"></i> Delete
            </a>
          </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<div class="bg-light d-flex justify-content-center ">
    {% else %}
    <h3>No Articles have been added.</h3>
    {% endif%}
    <a href="{{ url_for('blog.add_article') }}" class="btn btn-default btn-lg">
        <i class="fa fa-plus"></i>
        Add article
      </a>
</div>
    </div>
</div>
{% endblock %}

app/templates/blog/blog.html
<!-- app/templates/blog/blog.html -->

{% extends "base.html" %}

{% block title %}Blog Home{% endblock %}
{% block body %}
<main id="main">

   

    <!-- ======= Blog Section ======= -->
    <section id="blog" class="blog">
      <div class="container">

        <div class="row">

          <div class="col-lg-8 entries">
            {% for article in articles %}
            <article class="entry" data-aos="fade-up">

              <div class="entry-img">
                <img src="{{ url_for('static', filename='img/blog-1.jpg') }}" alt="" class="img-fluid">
                
              </div>

              <h2 class="entry-title">
                <a href="{{ url_for('blog.blogsinglepage') }}">{{article.title}}</a>
              </h2>

              <div class="entry-meta">
                <ul>
                  <li class="d-flex align-items-center"><i class="icofont-user"></i> <a href="blog-single.html">{{article.author}}</a></li>
                  <li class="d-flex align-items-center"><i class="icofont-wall-clock"></i> <a href="blog-single.html"><time datetime="2020-01-01">{{article.date}}</time></a></li>
                  <li class="d-flex align-items-center"><i class="icofont-comment"></i> <a href="blog-single.html">12 Comments</a></li>
                </ul>
              </div>

              <div class="entry-content">
                <p>
                  Similique neque nam consequuntur ad non maxime aliquam quas. Quibusdam animi praesentium. Aliquam et laboriosam eius aut nostrum quidem aliquid dicta.
                  Et eveniet enim. Qui velit est ea dolorem doloremque deleniti aperiam unde soluta. Est cum et quod quos aut ut et sit sunt. Voluptate porro consequatur assumenda perferendis dolore.
                </p>
                <div class="read-more">
                  <a href="{{ url_for('blog.blogsinglepage') }}">Read More</a>
                </div>
              </div>

            </article><!-- End blog entry -->
            {% endfor %}

            <article class="entry" data-aos="fade-up">

              <div class="entry-img">
                <img src="{{ url_for('static', filename='img/blog-1.jpg') }}" alt="" class="img-fluid">
                
              </div>

              <h2 class="entry-title">
                <a href="{{ url_for('blog.blogsinglepage') }}">Dolorum optio tempore voluptas dignissimos cumque fuga qui quibusdam quia reiciendis</a>
              </h2>

              <div class="entry-meta">
                <ul>
                  <li class="d-flex align-items-center"><i class="icofont-user"></i> <a href="blog-single.html">John Doe</a></li>
                  <li class="d-flex align-items-center"><i class="icofont-wall-clock"></i> <a href="blog-single.html"><time datetime="2020-01-01">Jan 1, 2020</time></a></li>
                  <li class="d-flex align-items-center"><i class="icofont-comment"></i> <a href="blog-single.html">12 Comments</a></li>
                </ul>
              </div>

              <div class="entry-content">
                <p>
                  Similique neque nam consequuntur ad non maxime aliquam quas. Quibusdam animi praesentium. Aliquam et laboriosam eius aut nostrum quidem aliquid dicta.
                  Et eveniet enim. Qui velit est ea dolorem doloremque deleniti aperiam unde soluta. Est cum et quod quos aut ut et sit sunt. Voluptate porro consequatur assumenda perferendis dolore.
                </p>
                <div class="read-more">
                  <a href="{{ url_for('blog.blogsinglepage') }}">Read More</a>
                </div>
              </div>

            </article><!-- End blog entry -->

            <article class="entry" data-aos="fade-up">

              <div class="entry-img">
                <img src="{{ url_for('static', filename='img/blog-2.jpg') }}" alt="" class="img-fluid">
              </div>

              <h2 class="entry-title">
                <a href="blog-single.html">Nisi magni odit consequatur autem nulla dolorem</a>
              </h2>

              <div class="entry-meta">
                <ul>
                  <li class="d-flex align-items-center"><i class="icofont-user"></i> <a href="blog-single.html">John Doe</a></li>
                  <li class="d-flex align-items-center"><i class="icofont-wall-clock"></i> <a href="blog-single.html"><time datetime="2020-01-01">Jan 1, 2020</time></a></li>
                  <li class="d-flex align-items-center"><i class="icofont-comment"></i> <a href="blog-single.html">12 Comments</a></li>
                </ul>
              </div>

              <div class="entry-content">
                <p>
                  Incidunt voluptate sit temporibus aperiam. Quia vitae aut sint ullam quis illum voluptatum et. Quo libero rerum voluptatem pariatur nam.
                  Ad impedit qui officiis est in non aliquid veniam laborum. Id ipsum qui aut. Sit aliquam et quia molestias laboriosam. Tempora nam odit omnis eum corrupti qui aliquid excepturi molestiae. Facilis et sint quos sed voluptas. Maxime sed tempore enim omnis non alias odio quos distinctio.
                </p>
                <div class="read-more">
                  <a href="blog-single.html">Read More</a>
                </div>
              </div>

            </article><!-- End blog entry -->

            <article class="entry" data-aos="fade-up">

              <div class="entry-img">
                <img src="static/img/blog-3.jpg" alt="" class="img-fluid">
              </div>

              <h2 class="entry-title">
                <a href="blog-single.html">Possimus soluta ut id suscipit ea ut. In quo quia et soluta libero sit sint.</a>
              </h2>

              <div class="entry-meta">
                <ul>
                  <li class="d-flex align-items-center"><i class="icofont-user"></i> <a href="blog-single.html">John Doe</a></li>
                  <li class="d-flex align-items-center"><i class="icofont-wall-clock"></i> <a href="blog-single.html"><time datetime="2020-01-01">Jan 1, 2020</time></a></li>
                  <li class="d-flex align-items-center"><i class="icofont-comment"></i> <a href="blog-single.html">12 Comments</a></li>
                </ul>
              </div>

              <div class="entry-content">
                <p>
                  Aut iste neque ut illum qui perspiciatis similique recusandae non. Fugit autem dolorem labore omnis et. Eum temporibus fugiat voluptate enim tenetur sunt omnis.
                  Doloremque est saepe laborum aut. Ipsa cupiditate ex harum at recusandae nesciunt. Ut dolores velit.
                </p>
                <div class="read-more">
                  <a href="blog-single.html">Read More</a>
                </div>
              </div>

            </article><!-- End blog entry -->

            <article class="entry" data-aos="fade-up">

              <div class="entry-img">
                <img src="static/img/blog-4.jpg" alt="" class="img-fluid">
              </div>

              <h2 class="entry-title">
                <a href="blog-single.html">Non rem rerum nam cum quo minus. Dolor distinctio deleniti explicabo eius exercitationem. Veniam eius velit ab ipsa quidem rem.</a>
              </h2>

              <div class="entry-meta">
                <ul>
                  <li class="d-flex align-items-center"><i class="icofont-user"></i> <a href="blog-single.html">John Doe</a></li>
                  <li class="d-flex align-items-center"><i class="icofont-wall-clock"></i> <a href="blog-single.html"><time datetime="2020-01-01">Jan 1, 2020</time></a></li>
                  <li class="d-flex align-items-center"><i class="icofont-comment"></i> <a href="blog-single.html">12 Comments</a></li>
                </ul>
              </div>

              <div class="entry-content">
                <p>
                  Aspernatur rerum perferendis et sint. Voluptates cupiditate voluptas atque quae. Rem veritatis rerum enim et autem. Saepe atque cum eligendi eaque iste omnis a qui.
                  Quia sed sunt. Ea asperiores expedita et et delectus voluptates rerum. Id saepe ut itaque quod qui voluptas nobis porro rerum. Quam quia nesciunt qui aut est non omnis. Inventore occaecati et quaerat magni itaque nam voluptas. Voluptatem ducimus sint id earum ut nesciunt sed corrupti nemo.
                </p>
                <div class="read-more">
                  <a href="blog-single.html">Read More</a>
                </div>
              </div>

            </article><!-- End blog entry -->

            <div class="blog-pagination">
              <ul class="justify-content-center">
                <li class="disabled"><i class="icofont-rounded-left"></i></li>
                <li><a href="#">1</a></li>
                <li class="active"><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#"><i class="icofont-rounded-right"></i></a></li>
              </ul>
            </div>

          </div><!-- End blog entries list -->

          <div class="col-lg-4">

            <div class="sidebar" data-aos="fade-left">

              <h3 class="sidebar-title">Search</h3>
              <div class="sidebar-item search-form">
                <form action="">
                  <input type="text">
                  <button type="submit"><i class="icofont-search"></i></button>
                </form>

              </div><!-- End sidebar search formn-->

              <h3 class="sidebar-title">Categories</h3>
              <div class="sidebar-item categories">
                <ul>
                  <li><a href="#">General <span>(25)</span></a></li>
                  <li><a href="#">Lifestyle <span>(12)</span></a></li>
                  <li><a href="#">Travel <span>(5)</span></a></li>
                  <li><a href="#">Design <span>(22)</span></a></li>
                  <li><a href="#">Creative <span>(8)</span></a></li>
                  <li><a href="#">Educaion <span>(14)</span></a></li>
                </ul>

              </div><!-- End sidebar categories-->
                 <div class="">
                  <h3 class="sidebar-title">Check out our social-links</h3>
                  <hr>
                  <div class="social-links text-center  text-md-right pt-3 pt-md-0">
                    <div class="d-flex p-2 bd-highlight"><a href="#" class="twitter"><i class="bx bxl-twitter"></i></a></div>
                    
                    
                    <hr>
                    <div class="d-flex p-2 bd-highlight"><a href="#" class="facebook"><i class="bx bxl-facebook"></i></a></div>
                    
                    <hr>
                    <div class="d-flex p-2 bd-highlight"><a href="#" class="instagram"><i class="bx bxl-instagram"></i></a></div>
                    
                    
                    
                    <hr>
                    <div class="d-flex p-2 bd-highlight"> <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a></div>
                    
                    <hr>
                  </div>
                
                          
              </div>
              
              <h3 class="sidebar-title">Recent Posts</h3>
              <div class="sidebar-item recent-posts">
                {% for article in articles %}
                <div class="post-item clearfix">
                  <img src="static/img/blog-recent-posts-1.jpg" alt="">
                  <h4><a href="{{ url_for('blog.blogsinglepage') }}">{{article.title}}</a></h4>
                  <time datetime="2020-01-01">{{article.date}}</time>
                </div>
                {% endfor %}

                <div class="post-item clearfix">
                  <img src="static/img/blog-recent-posts-2.jpg" alt="">
                  <h4><a href="blog-single.html">Quidem autem et impedit</a></h4>
                  <time datetime="2020-01-01">Jan 1, 2020</time>
                </div>

                <div class="post-item clearfix">
                  <img src="static/img/blog-recent-posts-3.jpg" alt="">
                  <h4><a href="blog-single.html">Id quia et et ut maxime similique occaecati ut</a></h4>
                  <time datetime="2020-01-01">Jan 1, 2020</time>
                </div>

                <div class="post-item clearfix">
                  <img src="static/img/blog-recent-posts-4.jpg" alt="">
                  <h4><a href="blog-single.html">Laborum corporis quo dara net para</a></h4>
                  <time datetime="2020-01-01">Jan 1, 2020</time>
                </div>

                <div class="post-item clearfix">
                  <img src="static/img/blog-recent-posts-5.jpg" alt="">
                  <h4><a href="blog-single.html">Et dolores corrupti quae illo quod dolor</a></h4>
                  <time datetime="2020-01-01">Jan 1, 2020</time>
                </div>

              </div><!-- End sidebar recent posts-->

              <h3 class="sidebar-title">Tags</h3>
              <div class="sidebar-item tags">
                <ul>
                  <li><a href="#">App</a></li>
                  <li><a href="#">IT</a></li>
                  <li><a href="#">Business</a></li>
                  <li><a href="#">Business</a></li>
                  <li><a href="#">Mac</a></li>
                  <li><a href="#">Design</a></li>
                  <li><a href="#">Office</a></li>
                  <li><a href="#">Creative</a></li>
                  <li><a href="#">Studio</a></li>
                  <li><a href="#">Smart</a></li>
                  <li><a href="#">Tips</a></li>
                  <li><a href="#">Marketing</a></li>
                </ul>

              </div><!-- End sidebar tags-->

            </div><!-- End sidebar -->

          </div><!-- End blog sidebar -->

        </div>

      </div>
    </section><!-- End Blog Section -->

  </main><!-- End #main -->

{% endblock %}

app/templates/blog/dash_index.html
{% import "bootstrap/utils.html" as utils %}
{% extends "home/dashboard.html" %}
{% block title %}Blog Dashboard{% endblock %}

{% block blog %}
<div class="row mb-3" >
    <div class="col-sm-6 ">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Special title treatment</h5>
          <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Special title treatment</h5>
          <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>
    </div>
  </div>
  <div class="row" >
    <div class="col-sm-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Special title treatment</h5>
          <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Special title treatment</h5>
          <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}